'use client';

import { useActionState } from 'react';
import type { AdminAction } from '@/components/admin/ActionButton';
import { initialAdminActionState } from '@/lib/admin/form';
import { es } from '@/locales/es';

const t = es.auth.admin.taxonomies;

/** Create form for sectors/categories/tags (slug generated by the DB). */
export function CreateTaxonomyForm({
  action,
  kind,
  withScope = false,
}: {
  action: AdminAction;
  kind: 'sector' | 'category' | 'tag';
  withScope?: boolean;
}) {
  const [state, formAction, pending] = useActionState(action, initialAdminActionState);

  return (
    <form action={formAction} noValidate className="flex flex-wrap items-end gap-3">
      <input type="hidden" name="kind" value={kind} />
      <label className="block text-sm font-medium text-gray-700">
        {t.name}
        <input
          name="name"
          required
          minLength={2}
          maxLength={80}
          placeholder={t.createPlaceholder}
          className="mt-1 block w-64 rounded-2xl border border-gray-300 px-4 py-2 text-sm text-ink placeholder:text-gray-400 focus:border-ink"
        />
      </label>
      {withScope && (
        <label className="block text-sm font-medium text-gray-700">
          {t.scope}
          <select
            name="scope"
            defaultValue="product"
            className="mt-1 block rounded-2xl border border-gray-300 px-4 py-2 text-sm text-ink focus:border-ink"
          >
            <option value="product">{t.scopeProduct}</option>
            <option value="service">{t.scopeService}</option>
          </select>
        </label>
      )}
      <button
        type="submit"
        disabled={pending}
        className="rounded-full bg-ink px-5 py-2 text-sm font-medium text-white transition-colors hover:bg-gray-800 disabled:opacity-50"
      >
        {t.create}
      </button>
      {state.status !== 'idle' && state.message && (
        <p
          role={state.status === 'error' ? 'alert' : 'status'}
          className={state.status === 'error' ? 'text-sm text-red-600' : 'text-sm text-gray-700'}
        >
          {state.message}
        </p>
      )}
    </form>
  );
}

/** Inline rename form (slug follows the new name automatically). */
export function RenameTaxonomyForm({
  action,
  id,
  currentName,
}: {
  action: AdminAction;
  id: string;
  currentName: string;
}) {
  const [state, formAction, pending] = useActionState(action, initialAdminActionState);

  return (
    <form action={formAction} noValidate className="flex items-center gap-2">
      <input type="hidden" name="id" value={id} />
      <label className="sr-only" htmlFor={`rename-${id}`}>
        {t.rename}
      </label>
      <input
        id={`rename-${id}`}
        name="name"
        defaultValue={currentName}
        required
        minLength={2}
        maxLength={80}
        className="block w-44 rounded-2xl border border-gray-300 px-3 py-1.5 text-sm text-ink focus:border-ink"
      />
      <button
        type="submit"
        disabled={pending}
        className="rounded-full border border-gray-300 px-3 py-1.5 text-xs font-medium text-gray-700 transition-colors hover:bg-gray-100 disabled:opacity-50"
      >
        {t.saveRename}
      </button>
      {state.status === 'error' && state.message && (
        <p role="alert" className="text-xs text-red-600">
          {state.message}
        </p>
      )}
    </form>
  );
}
