import type { SupabaseClient } from '@supabase/supabase-js';
import { z } from 'zod';

/**
 * Taxonomy management (task 4.5, spec admin-backoffice + taxonomies). Slugs
 * are generated by the database (stored generated columns), so creation only
 * sends the name. Deactivation is always soft (is_active) — history survives.
 */

export type TaxonomyKind = 'sector' | 'category' | 'tag';

const KIND_TABLE: Record<TaxonomyKind, string> = {
  sector: 'sectors',
  category: 'categories',
  tag: 'tags',
};

const nameSchema = z
  .string()
  .trim()
  .min(1, 'El nombre es obligatorio.')
  .min(2, 'El nombre debe tener entre 2 y 80 caracteres.')
  .max(80, 'El nombre debe tener entre 2 y 80 caracteres.');

const scopeSchema = z.enum(['product', 'service'], {
  errorMap: () => ({ message: 'El ámbito debe ser product o service.' }),
});

export type TaxonomyResult = { ok: true } | { ok: false; message: string };

const GENERIC_ERROR = 'No se pudo guardar la taxonomía. Inténtalo de nuevo.';

function isUniqueViolation(error: { code?: string; message?: string }): boolean {
  return error.code === '23505' || /duplicate key|unique constraint/i.test(error.message ?? '');
}

function duplicateMessage(kind: TaxonomyKind): string {
  const label = kind === 'sector' ? 'sector' : kind === 'category' ? 'categoría' : 'etiqueta';
  return `Ya existe ${kind === 'sector' ? 'un' : 'una'} ${label} con ese nombre.`;
}

function tableFor(kind: string): string | null {
  return kind in KIND_TABLE ? KIND_TABLE[kind as TaxonomyKind] : null;
}

export async function createSector(
  client: SupabaseClient,
  input: { name: string; sortOrder?: number },
): Promise<TaxonomyResult> {
  const name = nameSchema.safeParse(input.name);
  if (!name.success) return { ok: false, message: name.error.issues[0]?.message ?? '' };

  const { error } = await client
    .from('sectors')
    .insert({ name: name.data, sort_order: input.sortOrder ?? 0 });
  if (error) {
    if (isUniqueViolation(error)) return { ok: false, message: duplicateMessage('sector') };
    console.error('[createSector]', error.message);
    return { ok: false, message: GENERIC_ERROR };
  }
  return { ok: true };
}

export async function createCategory(
  client: SupabaseClient,
  input: { name: string; scope: 'product' | 'service'; sortOrder?: number },
): Promise<TaxonomyResult> {
  const name = nameSchema.safeParse(input.name);
  if (!name.success) return { ok: false, message: name.error.issues[0]?.message ?? '' };
  const scope = scopeSchema.safeParse(input.scope);
  if (!scope.success) {
    return { ok: false, message: 'El ámbito debe ser product o service.' };
  }

  const { error } = await client
    .from('categories')
    .insert({ name: name.data, scope: scope.data, sort_order: input.sortOrder ?? 0 });
  if (error) {
    if (isUniqueViolation(error)) {
      return { ok: false, message: duplicateMessage('category') };
    }
    console.error('[createCategory]', error.message);
    return { ok: false, message: GENERIC_ERROR };
  }
  return { ok: true };
}

export async function createTag(
  client: SupabaseClient,
  input: { name: string },
): Promise<TaxonomyResult> {
  const name = nameSchema.safeParse(input.name);
  if (!name.success) return { ok: false, message: name.error.issues[0]?.message ?? '' };

  const { error } = await client.from('tags').insert({ name: name.data });
  if (error) {
    if (isUniqueViolation(error)) return { ok: false, message: duplicateMessage('tag') };
    console.error('[createTag]', error.message);
    return { ok: false, message: GENERIC_ERROR };
  }
  return { ok: true };
}

export async function renameTaxonomy(
  client: SupabaseClient,
  kind: TaxonomyKind | string,
  id: string,
  name: string,
): Promise<TaxonomyResult> {
  const table = tableFor(kind);
  if (!table) return { ok: false, message: 'Taxonomía no válida.' };
  const parsed = nameSchema.safeParse(name);
  if (!parsed.success) return { ok: false, message: parsed.error.issues[0]?.message ?? '' };

  const { error } = await client.from(table).update({ name: parsed.data }).eq('id', id);
  if (error) {
    if (isUniqueViolation(error)) {
      return { ok: false, message: duplicateMessage(kind as TaxonomyKind) };
    }
    console.error('[renameTaxonomy]', error.message);
    return { ok: false, message: GENERIC_ERROR };
  }
  return { ok: true };
}

export async function setTaxonomyActive(
  client: SupabaseClient,
  kind: TaxonomyKind | string,
  id: string,
  isActive: boolean,
): Promise<TaxonomyResult> {
  const table = tableFor(kind);
  if (!table) return { ok: false, message: 'Taxonomía no válida.' };

  const { error } = await client.from(table).update({ is_active: isActive }).eq('id', id);
  if (error) {
    console.error('[setTaxonomyActive]', error.message);
    return { ok: false, message: GENERIC_ERROR };
  }
  return { ok: true };
}
