import { beforeEach, describe, expect, it } from 'vitest';
import { makeSupabaseClient } from '@/test/supabase-mock';
import {
  createCategory,
  createSector,
  createTag,
  renameTaxonomy,
  setTaxonomyActive,
} from '@/lib/server/backoffice/taxonomies';

type Result = { ok: boolean; message?: string };

let h: ReturnType<typeof makeSupabaseClient>;
beforeEach(() => {
  h = makeSupabaseClient({
    sectors: { row: { id: 's-1', name: 'Café y Cacao', slug: 'cafe-y-cacao', is_active: true } },
    categories: { row: { id: 'cat-1', name: 'Alimentos', scope: 'product', is_active: true } },
    tags: { row: { id: 't-1', name: 'orgánico', slug: 'organico', is_active: true } },
  });
});

describe('taxonomy creation (4.5)', () => {
  it('creates a sector (slug generated by the DB)', async () => {
    const result = (await createSector(h.client, { name: 'Turismo' })) as Result;
    expect(result.ok).toBe(true);
    expect(h.calls.inserts['sectors']?.[0]).toEqual({ name: 'Turismo', sort_order: 0 });
  });

  it('creates a category with its scope', async () => {
    const result = (await createCategory(h.client, {
      name: 'Transporte',
      scope: 'service',
    })) as Result;
    expect(result.ok).toBe(true);
    expect(h.calls.inserts['categories']?.[0]).toEqual({
      name: 'Transporte',
      scope: 'service',
      sort_order: 0,
    });
  });

  it('rejects a category with an invalid scope', async () => {
    const result = (await createCategory(h.client, {
      name: 'Raro',
      scope: 'otro' as 'product',
    })) as Result;
    expect(result.ok).toBe(false);
    expect(result.message).toContain('ámbito');
    expect(h.calls.inserts['categories']).toBeUndefined();
  });

  it('creates a tag', async () => {
    const result = (await createTag(h.client, { name: 'exportable' })) as Result;
    expect(result.ok).toBe(true);
    expect(h.calls.inserts['tags']?.[0]).toEqual({ name: 'exportable' });
  });

  it.each([
    ['', 'El nombre es obligatorio.'],
    ['A', 'El nombre debe tener entre 2 y 80 caracteres.'],
    ['X'.repeat(81), 'El nombre debe tener entre 2 y 80 caracteres.'],
  ])('validates the name %j → %s', async (name, message) => {
    const result = (await createSector(h.client, { name })) as Result;
    expect(result).toEqual({ ok: false, message });
  });

  it('maps a unique-violation to a friendly duplicate message', async () => {
    h = makeSupabaseClient({
      sectors: {
        error: { code: '23505', message: 'duplicate key value violates unique constraint' },
      },
    });
    const result = (await createSector(h.client, { name: 'Café y Cacao' })) as Result;
    expect(result).toEqual({ ok: false, message: 'Ya existe un sector con ese nombre.' });
  });
});

describe('renameTaxonomy (4.5)', () => {
  it('renames a sector', async () => {
    const result = (await renameTaxonomy(h.client, 'sector', 's-1', 'Café y Cacao XXL')) as Result;
    expect(result.ok).toBe(true);
    expect(h.calls.updates['sectors']?.[0]).toEqual({ name: 'Café y Cacao XXL' });
  });

  it('renames a tag or category through the same whitelist', async () => {
    await renameTaxonomy(h.client, 'category', 'cat-1', 'Alimentos y Bebidas');
    expect(h.calls.updates['categories']?.[0]).toEqual({ name: 'Alimentos y Bebidas' });
    await renameTaxonomy(h.client, 'tag', 't-1', 'ecológico');
    expect(h.calls.updates['tags']?.[0]).toEqual({ name: 'ecológico' });
  });

  it('refuses an unknown taxonomy kind (table-name whitelist)', async () => {
    const result = (await renameTaxonomy(h.client, 'companies', 'c-1', 'Hack')) as Result;
    expect(result.ok).toBe(false);
    expect(result.message).toContain('Taxonomía no válida');
    expect(h.calls.updates['companies']).toBeUndefined();
  });
});

describe('setTaxonomyActive (4.5: soft-deactivate preserves history)', () => {
  it('deactivates without deleting', async () => {
    const result = (await setTaxonomyActive(h.client, 'sector', 's-1', false)) as Result;
    expect(result.ok).toBe(true);
    expect(h.calls.updates['sectors']?.[0]).toEqual({ is_active: false });
    expect(h.calls.deletes['sectors']).toBeUndefined();
  });

  it('reactivates', async () => {
    const result = (await setTaxonomyActive(h.client, 'tag', 't-1', true)) as Result;
    expect(result.ok).toBe(true);
    expect(h.calls.updates['tags']?.[0]).toEqual({ is_active: true });
  });

  it('refuses an unknown taxonomy kind', async () => {
    const result = (await setTaxonomyActive(h.client, 'users', 'u-1', false)) as Result;
    expect(result.ok).toBe(false);
    expect(h.calls.updates['users']).toBeUndefined();
  });
});
